version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mdbesp
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./BDM:/data/db  # монтируем локальную папку BDM для хранения данных
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro  # скрипт инициализации (опционально)
    environment:
      - MONGO_INITDB_DATABASE=temperature_monitoring  # имя вашей БД
      # Если нужна аутентификация, раскомментируйте следующие строки
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=password

  python_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: temp-app:1.0
    container_name: py_tmp_app
    depends_on:
      - mongodb
    environment:
      - TZ=Asia/Tbilisi
      #- DB_NAME=${DB_NAME}
      #- MONGO_URI=${MONGO_URI}
    ports:
      - "5001:5001"
    volumes:
      - ./:/usr/src/app
